// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbfmturpclqponehhdjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZm10dXJwY2xxcG9uZWhoZGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5MDExODMsImV4cCI6MjA5MTQ3NzE4M30.PtD8JSfgqh41A_6GpMrbM7mzJ_G4OiKEcGZN3_Fgc34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});