// src/test/helpers/mock-dashboard-context.ts
export function createMockDashboardContext(overrides: Record<string, unknown> = {}) {
  return {
    user: { id: 'user-1' },
    chatbot: { id: 'chatbot-1', chatbot_name: 'Test Bot', is_active: false },
    ownerData: { reception_phone: '' },
    loading: false,
    qaPairs: [],
    rootQuestions: [],
    mainMenuCount: 0,
    subOptionCount: 0,
    isEnterprise: false,
    isEnterpriseClient: false,
    brand: null,
    ...overrides,
    editingChatbot: false,
    editChatbotForm: { chatbot_name: 'Test Bot', greeting_message: 'Hello', farewell_message: 'Bye' },
    hasWhatsappCreds: false,
    useTemplate: () => {},
    formatAmount: () => '$0',
    setEditingChatbot: () => {},
    handleEditChatbotFormChange: () => {},
    handleLogout: () => {},
    handleSaveWhatsapp: () => {},
    handleSaveChatbotEdit: () => {},
    handleStartEditChatbot: () => {},
    handleAddMainQuestion: () => {},
    handleDeleteQuestion: () => {},
    getChildren: () => [],
    showAddQuestion: false,
    setShowAddQuestion: () => {},
    mainQuestionForm: { question_text: '', answer_text: '', media_url: '', media_type: '' },
    mainButtonOptions: [],
    error: null,
    handleMainQuestionChange: () => {},
    handleMainButtonOptionChange: () => {},
    addMainButtonOptionField: () => {},
    removeMainButtonOptionField: () => {},
    savingMainQuestion: false,
    setMainQuestionForm: () => {},
    setMainButtonOptions: () => {},
    editingQuestion: null,
    editQuestionForm: { question_text: '', answer_text: '', media_url: '', media_type: '' },
    setEditQuestionForm: () => {},
    handleStartEditQuestion: () => {},
    handleSaveQuestionEdit: () => {},
    handleEditQuestionFormChange: () => {},
    setEditingQuestion: () => {},
    savingEdit: false,
    handleAddSubOptions: async () => false,
    subscription: null,
    whatsappForm: { whatsapp_business_number: '', whatsapp_api_token: '' },
    showToken: false,
    setShowToken: () => {},
    handleWhatsappFormChange: () => {},
    savingWhatsapp: false,
    goLiveLoading: false,
  }
}
